export const data = [
    {
        title: "Money Matters 3.0",
        imageUrl: "/mm.png",
        desc: "Money Matters is a platform that facilitates the easy splitting of expenses among groups. Users can utilize this platform to keep track of their expenses efficiently.",
        technologies: ["Next.js", "Tailwind CSS", "MySQL", "Prisma"],
        createdAt : "Dec 2023",
        href: "https://money-matters3.vercel.app/",
        ghref: "https://github.com/NegativE333/moneyMatters3.0",
    },
    {
        title: "Crypto Domains",
        imageUrl: "/crypto.png",
        desc: "The Crypto Domains Marketplace is a decentralized application (DApp) built on the Ethereum blockchain. It allows users to buy, sell, and manage crypto domains using smart contracts.",
        technologies: ["Next.js", "Tailwind CSS", "Ethereum", "Solidity", "Hardhat"],
        createdAt : "Sep 2023",
        href: "",
        ghref: "https://github.com/NegativE333/cryptoDomains2.0",
    },
    {
        title: "Money Matters 2.0",
        imageUrl: "/mm2.png",
        desc: "With Money Matters, users can efficiently manage their expenses and set reminders to stay organized and in control of their financial transactions.",
        technologies: ["Next.js", "Tailwind CSS", "Supabase"],
        createdAt : "Jun 2023",
        href: "https://money-matter2-0.vercel.app/",
        ghref: "https://github.com/NegativE333/MoneyMatter2.0",
    },
    {
        title: "loud",
        imageUrl: "/loud.png",
        desc: "A music streaming website using Next.js, complemented by the enhanced user interface crafted with Tailwind CSS.",
        technologies: ["Next.js", "Tailwind CSS"],
        createdAt : "Mar 2023",
        href: "https://loud2-0.vercel.app/auth",
        ghref: "https://github.com/NegativE333/loud2.0",
    },
    {
        title: "Movii",
        imageUrl: "/movii.png",
        desc: "The website Moviii offers information about your preferred film or television programme. Uses the TMDB API.",
        technologies: ["React.js", "SCSS", "TMDB API"],
        createdAt : "Apr 2023",
        href: "https://moviiiweb.netlify.app/",
        ghref: "https://github.com/NegativE333/moviii",
    },
    {
        title: "Otaku",
        imageUrl: "/otaku.png",
        desc: "Otaku is an anime streaming website built with Next JS.",
        technologies: ["Next.js", "Tailwind CSS", "Mongo DB"],
        createdAt : "Mar 2023",
        href: "https://otaku-seven.vercel.app/",
        ghref: "https://github.com/NegativE333/Otaku",
    },
]