export const data = [
    {
        title: "Money Matters 3.0",
        imageUrl: "/mm.png",
        desc: "Money Matters is a platform that facilitates the easy splitting of expenses among groups. Users can utilize this platform to keep track of their expenses efficiently.",
        technologies: ["Next.js", "Tailwind CSS", "MySQL", "Prisma"],
        createdAt : "Dec 2023",
        href: "https://money-matters3.vercel.app/",
        ghref: "https://github.com/NegativE333/moneyMatters3.0",
    },
    {
        title: "Crypto Domains",
        imageUrl: "/crypto.png",
        desc: "The Crypto Domains Marketplace is a decentralized application (DApp) built on the Ethereum blockchain. It allows users to buy, sell, and manage crypto domains using smart contracts.",
        technologies: ["Next.js", "Tailwind CSS", "Ethereum", "Solidity", "Hardhat"],
        createdAt : "Sep 2023",
        href: "",
        ghref: "https://github.com/NegativE333/cryptoDomains2.0",
    },
    {
        title: "Money Matters 2.0",
        imageUrl: "/mm2.png",
        desc: "With Money Matters, users can efficiently manage their expenses and set reminders to stay organized and in control of their financial transactions.",
        technologies: ["Next.js", "Tailwind CSS", "Supabase"],
        createdAt : "Jun 2023",
        href: "https://money-matter2-0.vercel.app/",
        ghref: "https://github.com/NegativE333/MoneyMatter2.0",
    },
    {
        title: "loud",
        imageUrl: "/loud.png",
        desc: "A music streaming website using Next.js, complemented by the enhanced user interface crafted with Tailwind CSS.",
        technologies: ["Next.js", "Tailwind CSS"],
        createdAt : "Mar 2023",
        href: "https://loud2-0.vercel.app/auth",
        ghref: "https://github.com/NegativE333/loud2.0",
    },
    {
        title: "Otaku",
        imageUrl: "/otaku.png",
        desc: "Otaku is an anime streaming website built with Next JS.",
        technologies: ["Next.js", "Tailwind CSS", "Mongo DB"],
        createdAt : "Mar 2023",
        href: "https://otaku-seven.vercel.app/",
        ghref: "https://github.com/NegativE333/Otaku",
    },
    {
        title: "Duolingo Clone",
        imageUrl: "/duolingo.png",
        desc: "The Duolingo clone is a web application built using Next.js and Tailwind CSS, offering a user experience similar to the popular language learning platform. Leveraging Drizzle for state management, PostgreSQL for database storage, and Stripe for payment processing, it provides an immersive language learning experience with interactive lessons, quizzes, and progress tracking.",
        technologies: ["Next.js", "Tailwind CSS", "Drizzle", "PostgreSQL", "Stripe"],
        createdAt : "Mar 2024",
        href: "https://duolingo-clone-pi.vercel.app/",
        ghref: "https://github.com/NegativE333/duolingo-clone",
    },
    {
        title: "Notion Clone",
        imageUrl: "/notion.png",
        desc: "Crafted a Notion clone with Next.js, Tailwind CSS, and Convex database. Replicating Notion's collaborative and flexible workspace, the project enables users to create, organize, and collaborate on documents seamlessly.",
        technologies: ["Next.js", "Tailwind CSS", "Convex"],
        createdAt : "Oct 2023",
        href: "https://notion-clone-fawn.vercel.app/",
        ghref: "https://github.com/NegativE333/notion-clone",
    },
    {
        title: "Miro Clone",
        imageUrl: "/miro.png",
        desc: "A collaborative whiteboard application, built with Next.js and Tailwind CSS, incorporating Convex and Liveblocks for real-time collaboration. Users can sketch, annotate, and collaborate seamlessly, fostering remote teamwork and ideation sessions with ease.",
        technologies: ["Next.js", "Tailwind CSS", "Convex", "Liveblocks"],
        createdAt : "Jan 2024",
        href: "https://miro-clone-tau.vercel.app/",
        ghref: "https://github.com/NegativE333/miro-clone",
    },
    {
        title: "Airbnb Clone",
        imageUrl: "/airbnb.png",
        desc: "Built an Airbnb clone with Next.js and Tailwind CSS, leveraging MongoDB for data storage. This project replicates Airbnb's key features, providing users with a seamless experience for property listing, searching, and booking.",
        technologies: ["Next.js", "Tailwind CSS", "Mongo DB"],
        createdAt : "Mar 2023",
        href: "https://rental-tau.vercel.app/",
        ghref: "https://github.com/NegativE333/airbnbClone",
    },
    {
        title: "Movii",
        imageUrl: "/movii.png",
        desc: "The website Moviii offers information about your preferred film or television programme. Uses the TMDB API.",
        technologies: ["React.js", "SCSS", "TMDB API"],
        createdAt : "Apr 2023",
        href: "https://moviiiweb.netlify.app/",
        ghref: "https://github.com/NegativE333/moviii",
    },
]